export const SELECT_BASE_PLAN = 'SELECT_BASE_PLAN';
export const REMOVE_BASE_PLAN = 'REMOVE_BASE_PLAN';
export const CHANGE_BASE_PLAN = 'CHANGE_BASE_PLAN';

export const SELECT_ADDON = 'SELECT_ADDON';

export const SELECT_STREAMING_DEVICE = 'SELECT_STREAMING_DEVICE';
export const REMOVE_STREAMING_DEVICE = 'REMOVE_STREAMING_DEVICE';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';